# Basics
name: "Development Notes"
description: "dev notes description"
url: "http://blog.jchobsononline.ca"
paginate: 10

# Conversion
markdown: kramdown
permalink: pretty
#highlighter: pygments

#Collections
collections:
  snippets:
    output: true
